export let images : Array<any>= [[

     "assets/img/concerts(horizontal)/concert.jpg",
     "assets/img/concerts(horizontal)/concert1.jpg",
     "assets/img/concerts(horizontal)/concert2.jpg",
     "assets/img/concerts(horizontal)/concert3.jpg",
     "assets/img/concerts(horizontal)/concert4.jpg",
     "assets/img/concerts(horizontal)/concert5.jpg",
     "assets/img/concerts(horizontal)/concert6.jpg",
     "assets/img/concerts(horizontal)/concert7.jpg",
     "assets/img/concerts(horizontal)/concert8.jpg",
    "assets/img/concerts(horizontal)/concert9.jpg",
], [
    "assets/img/portraits(vertical)/portrait.jpg",
    "assets/img/portraits(vertical)/portrait1.jpg",
    "assets/img/portraits(vertical)/portrait2.jpg",
    "assets/img/portraits(vertical)/portrait3.jpg",
    "assets/img/portraits(vertical)/portrait4.jpg",
    "assets/img/portraits(vertical)/portrait5.jpg",
    "assets/img/portraits(vertical)/portrait6.jpg",
    "assets/img/portraits(vertical)/portrait7.jpg",
    "assets/img/portraits(vertical)/portrait8.jpg",
     "assets/img/portraits(vertical)/portrait9.jpg",
], [
    "assets/img/still-life(vertical)/still_life.jpg",
    "assets/img/still-life(vertical)/still_life1.jpg",
    "assets/img/still-life(vertical)/still_life2.jpg",
    "assets/img/still-life(vertical)/still_life3.jpg",
    "assets/img/still-life(vertical)/still_life4.jpg",
    "assets/img/still-life(vertical)/still_life5.jpg",
    "assets/img/still-life(vertical)/still_life6.jpg",
    "assets/img/still-life(vertical)/still_life7.jpg",
    "assets/img/still-life(vertical)/still_life8.jpg",
     "assets/img/still-life(vertical)/still_life9.jpg",
], [
    "assets/img/vacation-family(horizontal)/vacation.jpg",
    "assets/img/vacation-family(horizontal)/vacation1.jpg",
    "assets/img/vacation-family(horizontal)/vacation2.jpg",
    "assets/img/vacation-family(horizontal)/vacation3.jpg",
    "assets/img/vacation-family(horizontal)/vacation4.jpg",
    "assets/img/vacation-family(horizontal)/vacation5.jpg",
    "assets/img/vacation-family(horizontal)/vacation6.jpg",
    "assets/img/vacation-family(horizontal)/vacation7.jpg",
    "assets/img/vacation-family(horizontal)/vacation8.jpg",
     "assets/img/vacation-family(horizontal)/vacation9.jpg",
], [
    "assets/img/wedding(horizontal)/wedding.jpg",
    "assets/img/wedding(horizontal)/wedding1.jpg",
    "assets/img/wedding(horizontal)/wedding2.jpg",
    "assets/img/wedding(horizontal)/wedding3.jpg",
    "assets/img/wedding(horizontal)/wedding4.jpg",
    "assets/img/wedding(horizontal)/wedding5.jpg",
    "assets/img/wedding(horizontal)/wedding6.jpg",
    "assets/img/wedding(horizontal)/wedding7.jpg",
    "assets/img/wedding(horizontal)/wedding8.jpg",
     "assets/img/wedding(horizontal)/wedding9.jpg",
], [
   "assets/img/landscapes(horizontal)/landscape.jpg",
   "assets/img/landscapes(horizontal)/landscape1.jpg",
   "assets/img/landscapes(horizontal)/landscape2.jpg",
   "assets/img/landscapes(horizontal)/landscape3.jpg",
   "assets/img/landscapes(horizontal)/landscape4.jpg",
   "assets/img/landscapes(horizontal)/landscape5.jpg",
   "assets/img/landscapes(horizontal)/landscape6.jpg",
   "assets/img/landscapes(horizontal)/landscape7.jpg",
   "assets/img/landscapes(horizontal)/landscape8.jpg",
    "assets/img/landscapes(horizontal)/landscape9.jpg",
]];